const {Submission,Analysis,Report}=require("../models");const {analyzeMedia,extractUrl,synthesize}=require("../services");const {searchSources}=require("../ragService");const {transcribeMedia}=require("../transcriptionService");const {inspectProvenance}=require("../provenanceService");const {extractDocumentText,indexDocument,searchDocument}=require("../documentService");const {searchClaim,searchSourceHistory}=require("../webSearchService");const {assessSourceCredibility}=require("../sourceCredibilityService");const {calculateCredibility}=require("../utils");
async function update(s,stage,progress,message){Object.assign(s,{status:"processing",currentStage:stage,progress,message});await s.save();}
async function runInvestigation(id,{demoCase}={}){const s=await Submission.findById(id);if(!s)throw Object.assign(new Error("SUBMISSION_NOT_FOUND"),{status:404});if(process.env.DEMO_MODE==="true"){const report=await Report.findOneAndUpdate({submissionId:s._id},{submissionId:s._id,summary:"Demo mode is enabled. No live evidence was collected.",verdict:demoCase==="false"?"LIKELY_FALSE":"SUPPORTED",credibilityScore:demoCase==="false"?32:82,confidenceLevel:"HIGH",scores:{claimCredibility:demoCase==="false"?25:88,sourceCredibility:70,evidenceAgreement:80},evidenceTrail:[{type:"demo",description:"Controlled demonstration result.",confidence:0,relationship:"neutral"}],uploadedDocument:{available:false,reason:"DEMO_MODE"},webEvidence:{available:false,reason:"DEMO_MODE",results:[]},sourceProfile:{available:false,reason:"DEMO_MODE"},reasoning:["Demo mode is enabled."],provenance:{available:false,reason:"DEMO_MODE"},isDemo:true},{upsert:true,new:true});Object.assign(s,{status:"completed",currentStage:"completed",progress:100,message:"Demo report generated."});await s.save();return report;}
await update(s,"claim_analysis",10,"Understanding the submitted claim.");const claim=s.claim.trim();let uploadedDocument={available:false,reason:"NOT_PROVIDED"};if(s.type==="document"){await update(s,"document_rag",25,"Reading and indexing the uploaded document.");const extracted=await extractDocumentText(s.fileUrl,s.fileMeta?.mimeType);if(extracted.available){const indexed=await indexDocument(s._id,extracted.text);const retrieved=await searchDocument(s._id,claim);uploadedDocument={...extracted,indexedChunks:indexed.chunks,retrievedChunks:retrieved.chunks};}else uploadedDocument=extracted;}
await update(s,"web_search",45,"Searching independent web and news evidence.");const webEvidence=await searchClaim(claim);let pageEvidence={available:false,reason:"NOT_AN_ARTICLE_URL"};if(s.type==="article_url"&&s.sourceUrl)pageEvidence=await extractUrl(s.sourceUrl);
await update(s,"source_credibility",58,"Checking the source's public history.");const publisher=s.sourceName||pageEvidence.publisher||webEvidence.results?.[0]?.publisher||null;const sourceHistory=await searchSourceHistory(publisher);const sourceProfile=assessSourceCredibility(sourceHistory,publisher);
await update(s,"knowledge_base",68,"Checking the curated knowledge base.");const knowledgeBase=await searchSources(claim);
await update(s,"forensic_analysis",76,"Checking available media forensic signals.");const forensic=s.type==="image"?await analyzeMedia(s.fileUrl):{available:false,reason:"NOT_APPLICABLE",score:null};
await update(s,"transcription",82,"Processing available audio evidence.");const transcript=["audio","video"].includes(s.type)?await transcribeMedia(s.fileUrl):{available:false,reason:"NOT_APPLICABLE",text:"",segments:[]};
await update(s,"evidence_synthesis",90,"Comparing evidence streams.");const synthesis=await synthesize({claim,uploadedDocument,webEvidence,sourceProfile,knowledgeBase,forensic,transcript,pageEvidence});const scores={claimCredibility:Number.isFinite(synthesis.claimCredibility)?synthesis.claimCredibility:null,sourceCredibility:sourceProfile.score,evidenceAgreement:Number.isFinite(synthesis.evidenceAgreement)?synthesis.evidenceAgreement:null,forensic:forensic.score,provenance:null};const finalScore=calculateCredibility(scores);
await update(s,"report_generation",96,"Generating the investigation report.");const provenance=inspectProvenance(s);const payload={submissionId:s._id,scores,credibilityScore:finalScore.credibilityScore,confidenceLevel:finalScore.confidenceLevel,verdict:synthesis.verdict,uploadedDocument,webEvidence,sourceProfile,forensicDetails:forensic,provenanceDetails:provenance,transcript,reasoning:synthesis.reasoning,evidenceTrail:synthesis.evidenceTrail};await Analysis.findOneAndUpdate({submissionId:s._id},payload,{upsert:true,new:true});const report=await Report.findOneAndUpdate({submissionId:s._id},{...payload,summary:synthesis.summary,transcript:transcript.segments||[],provenance,isDemo:false},{upsert:true,new:true});Object.assign(s,{status:"completed",currentStage:"completed",progress:100,message:"Report generated."});await s.save();return report;}
module.exports={runInvestigation};
