const mongoose = require("mongoose");
const scoreSchema = { claimCredibility: Number, sourceCredibility: Number, evidenceAgreement: Number, forensic: Number, provenance: Number };
const submissionSchema = new mongoose.Schema({ type: { type: String, enum: ["image", "video", "audio", "text", "article_url", "document"], required: true }, claim: { type: String, required: true }, sourceName: String, sourceUrl: String, fileUrl: String, fileMeta: Object, status: { type: String, default: "pending" }, currentStage: { type: String, default: "submission_received" }, progress: { type: Number, default: 0 }, message: String }, { timestamps: true });
const analysisSchema = new mongoose.Schema({ submissionId: { type: mongoose.Schema.Types.ObjectId, ref: "Submission", required: true, unique: true }, scores: scoreSchema, credibilityScore: Number, confidenceLevel: String, verdict: String, uploadedDocument: Object, webEvidence: Object, sourceProfile: Object, forensicDetails: Object, provenanceDetails: Object, transcript: Object, reasoning: [String], evidenceTrail: [Object] }, { timestamps: true });
const reportSchema = new mongoose.Schema({ submissionId: { type: mongoose.Schema.Types.ObjectId, ref: "Submission", unique: true }, summary: String, verdict: String, credibilityScore: Number, confidenceLevel: String, scores: scoreSchema, evidenceTrail: [Object], uploadedDocument: Object, webEvidence: Object, sourceProfile: Object, reasoning: [String], transcript: [Object], provenance: Object, isDemo: { type: Boolean, default: false } }, { timestamps: true });
const sourceSchema = new mongoose.Schema({ title: { type: String, required: true }, url: { type: String, required: true }, publisher: String, content: { type: String, required: true }, publishedAt: Date, category: String, credibility: Number, embedding: [Number], metadata: Object }, { timestamps: true });
const documentChunkSchema = new mongoose.Schema({ submissionId: { type: mongoose.Schema.Types.ObjectId, ref: "Submission", required: true, index: true }, chunkIndex: { type: Number, required: true }, text: { type: String, required: true }, embedding: { type: [Number], required: true } }, { timestamps: true });
documentChunkSchema.index({ submissionId: 1, chunkIndex: 1 }, { unique: true });
module.exports = { Submission: mongoose.model("Submission", submissionSchema), Analysis: mongoose.model("Analysis", analysisSchema), Report: mongoose.model("Report", reportSchema), Source: mongoose.model("Source", sourceSchema), DocumentChunk: mongoose.model("DocumentChunk", documentChunkSchema) };
